// <auto-generated />
using System;
using Homework.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homework.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Homework.Domain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "LT981088349522671550",
                            Balance = 100m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "LT981088349522671551",
                            Balance = 80m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "LT981088349522671552",
                            Balance = 110m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AccountNumber = "LT981088349522671553",
                            Balance = 10m,
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            AccountNumber = "LT981088349522671554",
                            Balance = 200m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Homework.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastName = "Crouch",
                            Name = "Dominick",
                            PersonalId = 10512158741L
                        },
                        new
                        {
                            Id = 2,
                            LastName = "Griffith",
                            Name = "Maegan",
                            PersonalId = 2022081770L
                        },
                        new
                        {
                            Id = 3,
                            LastName = "Smith",
                            Name = "Ryan",
                            PersonalId = 10710237512L
                        });
                });

            modelBuilder.Entity("Homework.Domain.Models.Account", b =>
                {
                    b.HasOne("Homework.Domain.Models.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Homework.Domain.Models.User", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
