// <auto-generated />
using Homework.WebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homework.WebApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210115153030_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Homework.WebApp.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PersonalId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNumber = "LT012345678901234567",
                            Balance = 0m,
                            PersonalId = 39112220001L,
                            UserLastName = "Jonaitis",
                            UserName = "Jonas",
                            User_id = 1
                        },
                        new
                        {
                            Id = 2,
                            AccountNumber = "LT012345678901234568",
                            Balance = 0m,
                            PersonalId = 39112220002L,
                            UserLastName = "Petraitis",
                            UserName = "Petras",
                            User_id = 2
                        },
                        new
                        {
                            Id = 3,
                            AccountNumber = "LT012345678901234569",
                            Balance = 0m,
                            PersonalId = 39112220003L,
                            UserLastName = "Antanaitis",
                            UserName = "Antanas",
                            User_id = 3
                        });
                });

            modelBuilder.Entity("Homework.WebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
